{% set name = "pcl" %}
{% set version = "1.14.1" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set sha256 = "5dc5e09509644f703de9a3fb76d99ab2cc67ef53eaf5637db2c6c8b933b28af6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pointcloudlibrary/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('pcl', max_pin='x.x.x') }}

requirements:
  ignore_run_exports_from:
    - xorg-libx11  # [linux]
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('libglvnd-devel') }}    # [linux]
    - {{ cdt('libglvnd-glx') }}      # [linux]
    - cmake
    - ninja                          # [win]
    - make                           # [unix]
    - pkgconfig
  host:
    - xorg-libxfixes                 # [linux]
    - flann
    - eigen
    - libboost-devel
    - qhull
    - vtk * qt*
    # We have also a vanilla dependency of vtk without pins so that conda-smithy correctly sets the
    # pin from conda-forge-pinnings
    - vtk
    - libpng
    - glew
    - qt-main  # [not ppc64le]
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
    - libglvnd-devel  # [linux]
    - libglx-devel  # [linux]
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
  run:
    - flann
    - qhull
    - vtk * qt*
    - glew

test:
  commands:
    - test -d $PREFIX/include/{{ name }}-{{ major_version }}.{{ minor_version }}/{{ name }}              # [not win] 
    - if not exist %LIBRARY_INC%\\{{ name }}-{{ major_version }}.{{ minor_version }}\\{{ name }} exit 1  # [win] 

about:
  home: http://www.pointclouds.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Point Cloud Library (PCL)
  description: |
    The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.
  doc_url: http://www.pointclouds.org
  dev_url: https://github.com/pointcloudlibrary/pcl

extra:
  recipe-maintainers:
    - chambbj
    - hobu
    - Tobias-Fischer
