conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: github_actions
  linux_64: github_actions
  linux_aarch64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
build_platform:
  osx_arm64: osx_arm64
  linux_aarch64: linux_64
test: native_and_emulated
